### ISSUE TITLE
Global Money Notes 缺了#14 和 #19

### ISSUE THREAD

**Issue by majiajin** [aseaday/GlobalMoneyNotes#1]
您好，Global Money Notes 缺了#14 和 #19，麻烦重新补充一下，谢谢！

**Comment by lalawuu** [comment]
I would fix it asap.

________________________________________
发件人: Jordi Ma ***@***.***>
发送时间: 2022年6月8日 11:02
收件人: aseaday/GlobalMoneyNotes
抄送: Subscribed
主题: [aseaday/GlobalMoneyNotes] Global Money Notes 缺了#14 和 #19 (Issue #1)

您好，Global Money Notes 缺了#14 和 #19，麻烦重新补充一下，谢谢！

―

**Comment by lalawuu** [comment]
Fixed and add a all in one documents for convinience.
Thx for you remind.
